version: '3.8'

services:
  database:
    image: mysql:8
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: quantum
      MYSQL_DATABASE: kanban
      MYSQL_USER: quantum
      MYSQL_PASSWORD: quantum
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: database
    ports:
      - "8080:8080"

volumes:
  mysql_data: